CREATE DATABASE IF NOT EXISTS inventoryDB;
USE inventoryDB;

CREATE TABLE IF NOT EXISTS inventory (
    itemID INT AUTO_INCREMENT PRIMARY KEY,
    itemName VARCHAR(255) NOT NULL,
    UPC VARCHAR(50) UNIQUE NOT NULL,
    quantity INT DEFAULT 0,
    price DECIMAL(10,2) DEFAULT 0.00
);
