CREATE DATABASE IF NOT EXISTS ordersDB;
USE ordersDB;

CREATE TABLE IF NOT EXISTS orders (
    orderID INT AUTO_INCREMENT PRIMARY KEY,
    custID INT NOT NULL,
    orderStatus VARCHAR(50) NOT NULL,
    orderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    orderContents TEXT NOT NULL
);

